Parameters:
  NameOfService:
    Description: Enter Service Name
    Type: String
  InstanceTypeParameter:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - m1.small
      - m1.large
  KeyName:
    Description: Choose KeyName
    Type: AWS::EC2::KeyPair::KeyName

Mappings:  
  AMIMap: 
      us-east-1:
        AMI: ami-0583d8c7a9c35822c
      us-west-1:
        AMI: ami-0bdb828fd58c52235
      eu-west-1:
        AMI: ami-047bb4163c506cd98
      ap-southeast-1:
        AMI: ami-08569b978cc4dfa10
      ap-northeast-1:
        AMI: ami-06cd52961ce9f0d85

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: !FindInMap [AMIMap , !Ref "AWS::Region" , "AMI"]
      KeyName: !Ref KeyName
      Tags:
        - Key: "IAC"
          Value: !Join [ "--" ,["Cloud" , "Formation"]]
        - Key: "Name"
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  PrintSomeInfo:
    Description: The DNSName of the backup load balancer
    Value: !GetAtt MyInstance.PublicDnsName